### ISSUE TITLE
MorphOS: missing debug.h

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#1]
This header does not exist in MorphOS
https://github.com/sodero/InstallerLG/blob/9a5d4946d0e7bd0672c0162f5a1630233c384e76/src/gui.c#L18

**Comment by sodero** [comment]
Oh, I haven't built this on MorphOS for a while (obviously). Patches are very welcome if you'd like to try it out on MorphOS. Ports are a very nice way of ironing out bugs.

Maybe I'll try to get this running on MorphOS and AmigaOS as well in the future. But right now I'm focused on AROS (simply because the other ones already have a working installer).

**Comment by polluks** [comment]
Indeed! :-)

**Comment by sodero** [comment]
Yes, a whitespace clean up would be nice!

**Comment by sodero** [comment]
I just fixed this one but I can't figure out how to manually resolve issues. I guess using 'resolves' or similar in the commit message is the normal way of doing this?
