### ISSUE TITLE
copyfiles does not fail

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#28]
`lock C: on`
`build/Installer "dist/InstallerLG installer"`
should fail...

**Comment by polluks** [comment]
ok, this fails
Installer "/dist/InstallerLG installer"

**Comment by sodero** [comment]
That's very strange. I need to look into that.

**Comment by polluks** [comment]
![version](https://image.ibb.co/nDwWDp/version.png)
Version 1.40 is MOSSYS:C/Installer!
BTW `version C:foo` is always `version MOSSYS:C/foo`.

**Comment by sodero** [comment]
I'm not entirely sure where to install things. Is C: the right place?

**Comment by polluks** [comment]
The behavior in this case is not easy to define. If it has no icon, it may go to C: but MorphOS also has SYS:Tools/Installer.info.

**Comment by polluks** [comment]
@sodero I don't want to open an issue, what do you think about stripping the exe?

**Comment by sodero** [comment]
I doesn't work on AROS, strip seems to break the exe, that's why it's not done in the Makefile. Perhaps dist/Makefile is a good place for this. An exception for AROS is needed.

**Comment by polluks** [comment]
I see. Since MorphOS 3.10 there's better debug support in LogTool, so we may keep the symbols in alpha.

**Comment by sodero** [comment]
Ok, now I know what's happening here. 

In the first case (build/Installer "dist/InstallerLG installer"), the script is executed from the top dir (where the CHANGELOG is located). Due to this, the Installer binary cannot be found and the file operation fails silently, it simply ignores the error and continues. This "feature" is required by some scripts and it's how the CBM Installer and the MorphOS installer work. In the second case, the binary is found and then copy will fail due to the lock.

There's quite a few "features" like this one and you can turn most of them of with an (set @strict 1) at the top of the script (or anywhere really, you can enable sloppy mode again using (set @strict 0) if required).

I enabled strict mode in the installer script so now "build/Installer dist/InstallerLG installer" will fail like it should.
