### ISSUE TITLE
vbcc test 2% failed

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#34]
I will append the result...

**Comment by sodero** [comment]
Great, please do!

Den fre 5 apr. 2019 14:42Stefan <notifications@github.com> skrev:

**Comment by polluks** [comment]
http://polluks.freeshell.org/download/tmp.lha

**Comment by sodero** [comment]
That's very interesting. Are you building and running on Linux?

BR,
Ola

Den lör 6 apr. 2019 kl 01:46 skrev Stefan <notifications@github.com>:

**Comment by polluks** [comment]
Still MorphOS. I was trying UnixDirsII but it was nearly the same.

**Comment by sodero** [comment]
One observation that probably will improve the results, define YYERROR_VERBOSE when you build parser, like in the GNU Makefile:

parser.o: parser.c            
        $(CC) $(CINC) $(CDEF) $(CGEN) -c $< -DYYERROR_VERBOSE   

There are some other confusing results, the ordering of things but maybe the above will change some of that.

**Comment by sodero** [comment]
Nice that the shell script runs on MorphOS BTW. I gave up with that on AROS.

**Comment by sodero** [comment]
I just realized that the tests depend on AMIGA *not* being defined when building. If you look at gui.c you'll see that all gui_* functions are stubs printing the results to stdout, and this is what the test shell script uses to verify the results.

In order to make this work we need a test target in the VBCC makefile. Perhaps we should replace #ifdef AMIGA in gui.c with #ifdef TEST or something like that. And always set TEST if AMIGA is not defined.

**Comment by polluks** [comment]
> In order to make this work we need a test target in the VBCC makefile. Perhaps we should replace #ifdef AMIGA in gui.c with #ifdef TEST or something like that. And always set TEST if AMIGA is not defined.

Would you like to change this?

**Comment by sodero** [comment]
Yes, I can do that now.

**Comment by sodero** [comment]
I encapsulated all code affecting testing, this is primarily GUI code but it's also other code that leads to unpredictable results when testing, mostly things depending on the host, such as memory available, the CPU, the locale and so on. If you define LG_TEST when building everything you'll get an installer without gui sending output to stdout, just like the tests expect it to be.

**Comment by polluks** [comment]
It's getting better, I have to fix call of DoSuperNew.

**Comment by sodero** [comment]
Good work!

**Comment by polluks** [comment]
1132 test(s) failed
1669 test(s) passed
[test.log](https://github.com/sodero/InstallerLG/files/3847278/test.log)

**Comment by sodero** [comment]
Looks like there's a problem with the setup part in many tests.

The test suites work like this:

1 - Before each test is executed, the first shell script snippet is executed to "set the stage", in this case we clean up (in case the prior execution was interupted) and then create the directory that we want to rename:

(rename "\_rn\_" "\_rm\_") ; "**rm -Rf \_rm\_ \_rn\_ && mkdir \_rn\_**","-1","test -d \_rm\_ && rm -Rf \_rm\_ \_rn\_"

2 - When / if the setup above is done, we execute the Installer script, which is the part up until ';':

**(rename "\_rn\_" "\_rm\_")** ; "rm -Rf \_rm\_ \_rn\_ && mkdir \_rn\_","-1","test -d \_rm\_ && rm -Rf \_rm\_ \_rn\_"

3 - After the Installer script has been executed, two checks are done. First of all, the output of Installer is compared to the second quoted string (-1 in this case). Then the last shell script snippet is executed, in this case we use 'test -d' to verify that we have a new directory with the right name and then we clean up so that the next test starts from 0:

(rename "\_rn\_" "\_rm\_") ; "rm -Rf \_rm\_ \_rn\_ && mkdir \_rn\_","**-1**","**test -d \_rm\_ && rm -Rf \_rm\_ \_rn\_**"

If there is a problem with the setup or the teardown / file system checks, **FAIL** will be the result. If setup and teardown work as they should but the execution of the Installer script produces the wrong output, **ERR** is shown. If an **ERR** is generated, an err.tmp.* file containing more information will be created. This err.tmp.* file can be executed directly to make bugfixing as convenient as possible.

**Comment by sodero** [comment]
When testing commands that involve the GUI in some way, cryptic strings representing the state of the GUI are shown. Also, there are some variables that can be set to mimic user input, \@yes, \@skip, \@back and so on.

**Comment by polluks** [comment]
@sodero The position of the 0 makes trouble, please take a look
````
; test.delete:68
(delete "_dl_" (prompt "p") (confirm) (optional force) (delopts force) (infos)) ; [touch _dl_ ; test -f _dl_ && rm -f _dl_]
; Actual result [0 Line 1: Missing option 'help']
; Expected result [Line 1: Missing option 'help' 0]
````

**Comment by sodero** [comment]
That's strange.

Is gui.c:3587 executed before eval.c:481 or is it the other way around? The error message is written to stderr and the '0' to stdout. Perhaps that could lead to some weird flushing problems.

**Comment by polluks** [comment]
Hmm, I added an `fflush(stdout)`, didn't help.

**Comment by sodero** [comment]
In what order are they executed?

**Comment by polluks** [comment]
````
/*
gcc:  stderr stdout 
vbcc: stdout stderr 
*/

#include <stdio.h>

main()
{
fprintf(stdout,"stdout ");
fprintf(stderr,"stderr ");
}
````

**Comment by sodero** [comment]
Interesting. I didn't know that stderr and stdout use different buffering schemes. In general stderr should flush ASAP but not in this case it seems. It's depends on the implementation though, so it's not really possible to claim that vbcc is doing it wrong, it's just a bit strange.

What happens if you add 'fflush(stderr);' after the 'fprintf' in gui.c:gui_error? The error message is supposed to come before the '0'.

**Comment by polluks** [comment]
gcc buffers stdout, stderr is not buffered at all.

**Comment by sodero** [comment]
I turned of stdout buffering as you suggested but now I realize that the stdout output seems to come before stderr when using VBCC so you could try to change that line to disable buffering of stderr instead since that seems to be buffered for some reason.

**Comment by sodero** [comment]
Changed it to stderr instead. Maybe it works now, writing code blindfolded is a good idea :-)

**Comment by polluks** [comment]
10% better :-)
[err.txt](https://github.com/sodero/InstallerLG/files/4291950/err.txt)

**Comment by sodero** [comment]
Nice!

You should get further improvements if you move the '-DYYERROR_VERBOSE' from the lexer to the parser in Makefile.vbcc, see 'Makefile'. All syntax error messages should be correct then.

**Comment by sodero** [comment]
The string thrashing looks strange. Maybe snprintf doesn't behave the way it should (it should terminate with a '\0'), I'll change the malloc to a calloc just in case.

**Comment by polluks** [comment]
> The string thrashing looks strange. Maybe snprintf doesn't behave the way it should (it should terminate with a '\0'), I'll change the malloc to a calloc just in case.

Indeed. http://sun.hasenbraten.de/vbcc/ says
"vclib: Fixed snprintf() and vsnprintf() for sizes exactly matching the source."

**Comment by sodero** [comment]
I did some small adjustments to get it running with gcc (on MorphOS) as well. 80% passed, still lots of problems but it's not to bad. Hopefully my adjustments won't cause any vbcc problems.

**Comment by sodero** [comment]
97.7% pass now (MOS + gcc)..

**Comment by sodero** [comment]
98.2%

**Comment by sodero** [comment]
98.8%

It's been really useful to have these running on MorphOS btw, two bugs found and fixed sofar.

**Comment by sodero** [comment]
99.999013%

**Comment by sodero** [comment]
100% on both MorphOS and AmigaOS 4 now. Took a while :)
