### ISSUE TITLE
RCFTPd: syntax error

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#37]
Line 757
	(if (>= @user-level 2)(confirm))
http://aminet.net/package/comm/tcp/rc-ftpd

**Comment by sodero** [comment]
Thanks! I'll have a look.

**Comment by sodero** [comment]
Fixed, but not commited yet, the tree is in a bit of a mess.

The script construct is strange though. It's possible to achieve the exact same thing with just "(confirm 2)". And "(if (>= @user-level 1) (confirm))" (which is used in other places in the script) won't result in a confirmation since the default threshold of confirm is 2 (so instead of "(confirm 2)", a plain "(confirm)" can be used).

Nevertheless, the code exists, so we should support it. Even though it might not do exactly what the author intended.

**Comment by sodero** [comment]
Fixed in c4f7f32cee511ad906e0fe5396654ebe74a0b02b

**Comment by sodero** [comment]
Nope. I messed up. Need to try again.

**Comment by sodero** [comment]
Ok, now it's better.
